# Generated by Django 5.2.8 on 2025-12-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='основний', max_length=50),
        ),
    ]
