# Generated by Django 5.2.8 on 2025-12-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
