# Generated by Django 5.2.8 on 2025-12-04 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_lesson_item_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='theory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theorypractice',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='theorypractice',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.item'),
        ),
    ]
