# Generated by Django 5.2.8 on 2025-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    # Changed to depend on the initial migration and be a no-op because the
    # repository currently contains the models with these fields already
    # present. This avoids migration conflicts while preserving the file so
    # history isn't lost. If you have the original migration operations,
    # restore them here instead.
    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = []