# Generated by Django 5.2.8 on 2025-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_item_theory_theorypractice_image_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="name_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="theme_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="theme_uk",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="name_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="name_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
