# Generated by Django 5.0.1 on 2025-12-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_item_theory_theorypractice_image_path_and_more'),
        ('education', '0005_grade_name_de_grade_theme_de_grade_theme_uk_and_more'),
    ]

    operations = [
    ]
