# Generated by Django 5.2.8 on 2025-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_merge_20251208_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='theory',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='map_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='map_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='map_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='map_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
