# Generated by Django 5.0.1 on 2026-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
